### PR TITLE
Feat toggle

### PR DESCRIPTION
**Pull request by brauliorivas**
BEGINRELEASENOTES
- A toggle switch has been added to switch between a particle's PDG or name 
- If activated, every loaded particle image is updated using `updateTexImg` function from `js/object.js/InfoBox` class. 
- Then the canvas is re-drawn with the updated particles using `drawAll` function from `js/main.js` 

ENDRELEASENOTES
This work is related to #11. PR #11 should be merged first. I had to start from there to prevent some merge conflicts.

### CODE REVIEW

**Comment by kjvbrt** [comment]
This looks nice :)

Can you add label text next to the toggle itself?

**Comment by tmadlener** [comment]
I have also enabled the possibility to easily rebase this onto the master branch for the repository.

**Comment by brauliorivas** [comment]
> Can you add label text next to the toggle itself?

Sure, I'm going to add this.

**Comment by kjvbrt** [comment]
The initial label is "Names" but after toggling on/off it is "Name".

I would prefer to have this constant, something like: `Show PDG IDs`

**Pull request merged**
