### PR TITLE
Fix previews workflow

### PR DESCRIPTION
**Pull request by brauliorivas**
BEGINRELEASENOTES
- PR previews should now work, using the updated `preview.yml` file.

ENDRELEASENOTES
After taking a closer look, [pr-preview-action](https://github.com/rossjrw/pr-preview-action) uses another github action called [sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment). So I came across issue [#930](https://github.com/marocchino/sticky-pull-request-comment/issues/930) where happened the same error. So the solution is proposed by the author like [this](https://github.com/marocchino/sticky-pull-request-comment/issues/930#issuecomment-1483687007).

### CODE REVIEW

**Comment by brauliorivas** [comment]
Oh It didn't work. I know why now. It "worked" [before](https://github.com/key4hep/dmx/pull/21) for @tmadlener because it was a PR inside the same dmX repo (the gh preview worked). However, when PR's are opened from a fork, then It fails, because it doesn't have enough permissions to push the preview code from the fork to the upstream. The author of [pr-preview-action](https://github.com/rossjrw/pr-preview-action) suggest to change the type of event, from `pull_request` to `pull_request_target` as explained [here](https://github.com/rossjrw/pr-preview-action/issues/3). Now I have changed it but isn't triggering. I'll try to simulate this with my own org and make a fork of the repo to my own account to test how to get this to work. Also, in theory changing the permissions for PR to write should enable github-actions bot to add the link of the preview as a commentary.

**Comment by brauliorivas** [comment]
The new workflow is not triggering but should in theory. I've replicated the same situation using a repo from an [organization](https://github.com/JavascriptMadness/home) and a [fork](https://github.com/brauliorivas/home).
So in [PR #7](https://github.com/JavascriptMadness/home/pull/7), it couldn't deploy to gh pages because of this [error](https://github.com/JavascriptMadness/home/actions/runs/9143118965/job/25139408325#step:3:167). 
In dmX happens the same: [here](https://github.com/key4hep/dmx/actions/runs/9135528103/job/25124432719#step:3:167)

But after changing the trigger to `pull_request_target`, it [worked](https://github.com/JavascriptMadness/home/pull/8#issuecomment-2119021107) using the updated [workflow file](https://github.com/JavascriptMadness/home/actions/runs/9143128900/workflow#L5-L14). I guess that PR #22 won't deploy either because are using other workflow file, but from now on we can test if this finally works.

**Comment by tmadlener** [comment]
Thanks for investigating this and writing everything up so that we have a comprehensive list of things to check when we run into this the next time ;) 

Did I understand correctly, that we need to merge this first to see if it actually fixes things?

> So we would need to run the workflows only under approval (first-time contributors maybe).

We do that in any case for all our repositories.

**Comment by brauliorivas** [comment]
> Did I understand correctly, that we need to merge this first to see if it actually fixes things?
> 
> >

I guess... I mean, in my example it worked. But maybe some other thing could cause an error. So I would like to give it a try, and if doesn't work, then I will see what happens and try to fix it, again 😅.

> We do that in any case for all our repositories.

Ohh, then it's fine.

**Comment by tmadlener** [comment]
Then let's merge and see what happens ;)

**Pull request merged**
